# Change these first
owner: gameflow-tv # Your GitHub organization or username, where this repository lives
repo: status.gameflow.tv # The name of this repository

sites:
  - name: Gameflow.tv
    url:  https://gameflow.tv
    icon: https://gameflow.tv/favicon.ico
    #headers:
    #  - "Content-Type: application/json"
    #body: '{ "status": "ok" }'
  - name: Backend
    url: https://api.gameflow.tv/health
    icon: https://gameflow.tv/favicon.ico
    #headers:
    #  - "Content-Type: application/json"
    body: '{"status":"UP"}'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gameflow.tv
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Gameflow Statuspage
  theme: dark
  introTitle: "**Gameflow service status**"
  introMessage: If you beleive there is an incedent that our system have not picked up pleas contact us on discord!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
