owner: gameflow-tv 
repo: status.gameflow.tv 

sites:
  - name: Gameflow.tv
    url:  https://gameflow.tv
    icon: https://app.gameflow.tv/favicon.ico
  - name: Gameflow API
    url: https://api.gameflow.tv/.well-known/apollo/server-health
    icon: https://app.gameflow.tv/favicon.ico
    #headers:
    #  - "Content-Type: application/json"
    body: '{"status":"pass"}'

status-website:
  cname: status.gameflow.tv
  logoUrl: https://static.gameflow.tv/icon.svg
  name: Gameflow status page
  theme: dark
  introTitle: "**Gameflow service status**"
  introMessage: If you believe there is an incident that our system have not picked up please contact us on Discord!
  navbar:
    - title: Status
      href: /
